### ISSUE TITLE
Upgrade Spray dependency to v1.3.2

### ISSUE THREAD

**Issue by utgarda** [dlouwers/reactive-consul#9]
Currently doesn't work with spray-json 1.3.2:

```
java.lang.NoSuchMethodError: stormlantern.consul.client.dao.ConsulHttpProtocol.optionFormat(Lspray/json/JsonFormat;)Lspray/json/StandardFormats$OptionFormat;
java.lang.NoSuchMethodError: stormlantern.consul.client.dao.ConsulHttpProtocol.optionFormat(Lspray/json/JsonFormat;)Lspray/json/StandardFormats$OptionFormat;
        at stormlantern.consul.client.dao.ConsulHttpProtocol$class.$init$(ConsulHttpProtocol.scala:38)
        at stormlantern.consul.client.dao.SprayConsulHttpClient.<init>(SprayConsulHttpClient.scala:19)
```

Is it possible to upgrade the dependency version?

**Comment by dlouwers** [comment]
Spray version is now 1.3.2, hope that helps.
